# Generated by Django 4.0.1 on 2022-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.TextField(default=1, verbose_name='lang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(default=1, verbose_name='link'),
            preserve_default=False,
        ),
    ]
